#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sys import exit

from lib.config import Config
from lib.amazonwish import Scrapper

from lxml.html import tostring

class Main:
    def __init__(self):
        country = 'us'
        scrapy = Scrapper()
        params = scrapy.readConfig(country)
        page = scrapy.downloadPage(params,'3MCYFXCFDH4FA')

        titles = scrapy.titles(page)
        covers = scrapy.covers(page)
        authors = scrapy.authors(page)
        prices = scrapy.prices(page)
        via = scrapy.via(page)

        for entry in titles: 
            res = tostring(entry, encoding='utf-8', method='text', pretty_print=True).strip()
            print res

if __name__ == "__main__":
    Main()
